config/routes.rb
Rails.application.routes.draw do
  resources :elevators
  resources :columns
  resources :addresses
  resources :batteries
  resources :buildingdetails
  resources :buildings
  resources :customers
  resources :leads
  resources :quotes
#  get 'home/index' #devise tutorial default "landing page"
  root to: "pages#index"
  #devise_for :users
  devise_for :users, :controllers => { :registrations => 'signups' }
  #resources :users
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#  root 'pages#index'
  get 'commercial' => 'pages#commercial'
  get 'residential' => 'pages#residential'
  get 'quote' => 'pages#quote'
  get 'index' => 'pages#index'
  get 'signups-auth' => 'pages#signups-auth'
  post 'signups-auth', action: :create, controller: "passwords"

#  get 'users/:id' => 'users#show', as: :user
#  post 'sign_up' => 'users#show'

  authenticate :user do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get 'welcome' => redirect('/admin')

    resources :interventions
    get 'get_form_customer_selector', action: :get_form_customer_selector, controller: 'interventions'
    get 'get_form_building_selector', action: :get_form_building_selector, controller: 'interventions'
    get 'get_form_battery_selector',  action: :get_form_battery_selector,  controller: 'interventions'
    get 'get_form_column_selector',   action: :get_form_column_selector,   controller: 'interventions'
    get 'get_form_elevator_selector', action: :get_form_elevator_selector, controller: 'interventions'
    
  end


end

app/models/address.rb
class Address < ApplicationRecord
    has_one :customer
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    belongs_to :employee
    has_many :column
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    belongs_to :address
    has_one :buildingdetail
    has_one :battery
    has_one :employee
end

app/models/column.rb
class Column < ApplicationRecord
    #self.inheritance_column = :_type_disabled
    has_many :elevator
    belongs_to :battery
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :address
    belongs_to :user
    has_many :building
end

app/models/dim_customer.rb
class DimCustomer < PostgresRecord
end

app/models/elevator.rb
class Elevator < ApplicationRecord
  #self.inheritance_column = :_type_disabled
  belongs_to :column
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
end

app/models/fact_contact.rb
class FactContact < PostgresRecord
end

app/models/fact_elevator.rb
class FactElevator < PostgresRecord
end

app/models/fact_quote.rb
class FactQuote < PostgresRecord
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :attachment
    def attachment_blob_id
#        self.attachment.blob_id
        self.attachment.blob_id
    end
end

#    if self.attachment.blob_id
#        def attachment_blob_id
#            self.attachment.blob_id
#        end
#    else
#        def attachment_blob_id
#            return "-"
#        end
#    end

#    scope :attachment_blob_id, -> { where(self.attachment.blob_id) }
#
#    def attachment_blob_id?
#        self.attachment.blob_id
#    end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
#  belongs_to :employees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :employee
  has_one :customer
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]

  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @employees = Employee.order(:first_name)
    @intervention = Intervention.new
  end

  # GET /interventions/1/edit
  def edit
    @employees = Employee.order(:first_name)
    @intervention = Intervention.find(params[:id])
  end

  def get_form_customer_selector
    employee_id = params[:employee_id]
    @customers = Customer.where(user_id: employee_id)
    render partial: 'step-1', locals: { customers: @customers }
  end

  def get_form_building_selector
    customer_id = params[:customer_id]
    @buildings = Building.where(customer_id: customer_id)
    render partial: 'step-2', locals: { buildings: @buildings }
  end

  def get_form_battery_selector
    building_id = params[:building_id]
    @batteries = Battery.where(building_id: building_id)
    render partial: 'step-3', locals: { batteries: @batteries }
  end
  
  def get_form_column_selector
    battery_id = params[:battery_id]
    @columns = Column.where(battery: battery_id)
    render partial: 'step-4', locals: { columns: @columns }
  end

  def get_form_elevator_selector
    column_id = params[:column_id]
    @elevators = Elevator.where(column_id: column_id)
    render partial: 'step-5', locals: { elevators: @elevators }
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save
        format.html { redirect_to @intervention, notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to @intervention, notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy
    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date_and_time_of_the_intervention, :end_date_and_time_of_the_intervention, :result, :report, :status)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: @intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- INTERVENTIONS -->

  <section id="interventions">
    <div class="container">
       <header class="mb-60">
       <!--
        <h2 class="text-center">Interventions Form</h2>
        -->
        <p class="lead font-lato"></p>
        <hr/>
       </header>       

          <section id='step-0'>

            <div class='row'>
              <h3>Identification</h3>
              <h4>Employee Selection</h4>
              <p>Select your credentials</p>

              <style>
                section{
                  padding:0;
                  border-bottom:none;
                } 
                section>div.row{
                  margin:10px 10px 80px 10px !important;
                }
                section div.row h4{
                  display:none;
                }
                hr{
                  display:none;
                }
              </style>
              <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
              <script>
                jQuery(function($) {
                  $("#step-1").html("");
                  $("#hidden-employee").val("");
                  $("#select-employee").on("change",function() {
                      var selectVal = $(this).val(); 
                      if (selectVal != -1){
                        if($("#step-1").html() != ""){
                          $("#step-1").html("");
                          $("#hidden-employee").val("");
                        }
                        $.ajax({
                          url: "/get_form_customer_selector",
                          data: {"employee_id":selectVal},
                          success: function(data){
                            $("#step-1").html(data);
                            $("#hidden-employee").val(selectVal);
                          }
                        }).done(function() {

                        });
                      }else{
                        $("#step-1").html("");
                      }
                  });
                });
              </script>
              <input type="hidden" id="hidden-employee" name="intervention[employee_id]" value="<%=  %>">
              <select name="intervention[author]" id='select-employee' class="form-select" aria-label="select example" autocomplete="off" >

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@employees.nil? %>
                <% @employees.each do |employee| %>

                  <option value="<%= employee.id %>">
                    <%= employee.first_name %> <%= employee.last_name %>
                  </option>

                <% end %>
              <% end %>

              </select>
            </div>
          </section>
              <script>
                jQuery(function($) {
                  $("#step-2").html("");
                });
              </script>
          <section id="step-1">
          </section>
              <script>
                jQuery(function($) {
                  $("#step-3").html("");
                });
              </script>
          <section id='step-2'>
          </section>
              <script>
                jQuery(function($) {
                  $("#step-4").html("");
                });
              </script>
          <section id="step-3">
          </section>
              <script>
                jQuery(function($) {
                  $("#step-5").html("");
                });
              </script>
          <section id='step-4'>
          </section>

          <section id="step-5">
          </section>
          <section id="step-6">
            <div class='row'>
              <hr/>
              <h3>Description</h3>
              <h4>Intervention Description</h4>
              <p>Please describe the nature of the intervention</p>
              <!--
              <label for="intervention-description" class="form-label">Intervention description.</label>
              -->
              <textarea name="intervention[report]" class="form-control" id="intervention-description" rows="3" autocomplete="off"></textarea>
            </div>
          </section>

    </div>
  </section>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interventions/_step-1.html.erb
<script>
                jQuery(function($) {
                  $("#select-customer").on("change",function() {
                      var selectVal = $(this).val(); 
                      if (selectVal != -1){
                        if($("#step-2").html() != ""){
                          $("#step-2").html("");
                        }
                        $.ajax({
                          url: "/get_form_building_selector",
                          data: {"customer_id":selectVal},
                          success: function(data){
                            $("#step-2").html(data);
                          }
                        }).done(function() {                             
                        });
                      }else{
                        $("#step-2").html("");
                      }
                  });
                });
</script>
            <div class='row'>
              <h4>Step 1/5</h4>
              <p>Select Customer</p>
              <select name="intervention[customer_id]" id="select-customer" class="form-select" aria-label="select example" autocomplete="off">

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@customers.nil? %>
                <% @customers.each do |customer| %>

                  <option value="<%= customer.id %>">
                    <%= customer.company_name %>
                  </option>

                <% end %>
              <% end %>


              </select>
            </div>

app/views/interventions/_step-2.html.erb
<script>
                jQuery(function($) {
                  $("#select-building").on("change",function() {
                      var selectVal = $(this).val(); 
                      if (selectVal != -1){
                        if($("#step-3").html() != ""){
                          $("#step-3").html("");
                        }
                        $.ajax({
                          url: "/get_form_battery_selector",
                          data: {"building_id":selectVal},
                          success: function(data){
                            $("#step-3").html(data);
                          }
                        }).done(function() {

                        });
                      }else{
                        $("#step-3").html("");
                      }
                  });
                });
</script>
            <div class='row'>
              <h4>Step 2/5</h4>
              <p>Select Building</p>
              <select  name="intervention[building_id]" id="select-building" class="form-select" aria-label="select example" autocomplete="off">

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@buildings.nil? %>
                <% @buildings.each do |building| %>

                  <option value="<%= building.id %>">
                    <%= building.id %>
                  </option>

                <% end %>
              <% end %>

              </select>
            </div>

app/views/interventions/_step-3.html.erb
<script>
                jQuery(function($) {
                  $("#select-battery").on("change",function() {
                      var selectVal = $(this).val(); 
                      if (selectVal != -1){
                        if($("#step-4").html() != ""){
                          $("#step-4").html("");
                        }
                        $.ajax({
                          url: "/get_form_column_selector",
                          data: {"battery_id":selectVal},
                          success: function(data){
                            $("#step-4").html(data);
                          }
                        }).done(function() {

                        });
                      }else{
                        $("#step-4").html("");
                      }
                  });
                });
</script>
            <div class='row'>
              <h4>Step 3/5</h4>
              <p>Select Battery</p>
              <select  name="intervention[battery_id]" id="select-battery" class="form-select" aria-label="select example" autocomplete="off">

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@batteries.nil? %>
                <% @batteries.each do |battery| %>

                  <option value="<%= battery.id %>">
                    <%= battery.id %>
                  </option>

                <% end %>
              <% end %>
              </select>
            </div>

app/views/interventions/_step-4.html.erb
<script>
                jQuery(function($) {
                  $("#select-column").on("change",function() {
                      var selectVal = $(this).val(); 
                      if (selectVal != -1){
                        if($("#step-5").html() != ""){
                          $("#step-5").html("");
                        }
                        $.ajax({
                          url: "/get_form_elevator_selector",
                          data: {"column_id":selectVal},
                          success: function(data){
                            $("#step-5").html(data);
                          }
                        }).done(function() {

                        });
                      }else{
                        $("#step-5").html("");
                      }
                  });
                });
</script>
            <div class='row'>
              <h4>Step 4/5</h4>
              <p>Select Column</p>
              <select  name="intervention[column_id]" id="select-column" class="form-select" aria-label="select example" autocomplete="off">

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@columns.nil? %>
                <% @columns.each do |column| %>

                  <option value="<%= column.id %>">
                    <%= column.id %>
                  </option>

                <% end %>
              <% end %>
              </select>
            </div>

app/views/interventions/_step-5.html.erb
            <div class='row'>
              <h4>Step 5/5</h4>
              <p>Select Elevator</p>
              <select  name="intervention[elevator_id]" id="select-elevator" class="form-select" aria-label="select example" autocomplete="off">

                  <option selected value='-1'>
                    None
                  </option>

              <% if !@elevators.nil? %>
                <% @elevators.each do |elevator| %>

                  <option value="<%= elevator.id %>">
                    <%= elevator.id %>
                  </option>

                <% end %>
              <% end %>

              </select>
            </div>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td style="font-style:italic;">
          Author ID:    <%= intervention.author %>,
          Building ID,  <%= intervention.building_id %>
          Battery ID:   <%= intervention.battery_id %>,
          Column ID,    <%= intervention.column_id %>
          Elevator ID:  <%= intervention.elevator_id %>,
          Employee ID,  <%= intervention.employee_id %>
          Start Time:   <%= intervention.start_date_and_time_of_the_intervention %>,
          End Time:     <%= intervention.end_date_and_time_of_the_intervention %>
          Result:       <%= intervention.result %>,
          Report:       [<%= intervention.report %>],
          Status:       <%= intervention.status %>
        &nbsp;
        </td>
        <td style="font-weight:bold;text-decoration:underline;"><%= link_to 'Show', intervention %></td>
        <td>&nbsp;</td>
        <td style="font-weight:bold;text-decoration:underline;"><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td>&nbsp;</td>
        <td style="font-weight:bold;text-decoration:underline;"><%= link_to "delete", intervention_path(intervention), method: :delete %>&nbsp;</td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', interventions_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>
<!-- DISPLAY INTERVENTION HERE -->
<p>
              Author ID:    <%= @intervention.author %>,
<br>          Building ID,  <%= @intervention.building_id %>
<br>          Battery ID:   <%= @intervention.battery_id %>,
<br>          Column ID,    <%= @intervention.column_id %>
<br>          Elevator ID:  <%= @intervention.elevator_id %>,
<br>          Employee ID,  <%= @intervention.employee_id %>
<br>          Start Time:   <%= @intervention.start_date_and_time_of_the_intervention %>,
<br>          End Time:     <%= @intervention.end_date_and_time_of_the_intervention %>
<br>          Result:       <%= @intervention.result %>,
<br>          Report:       [<%= @intervention.report %>],
<br>          Status:       <%= @intervention.status %>
</p>
<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>