config/routes.rb
Rails.application.routes.draw do
  resources :elevators
  resources :columns
  resources :addresses
  resources :batteries
  resources :buildingdetails
  resources :buildings
  resources :customers
  resources :leads
  resources :quotes
#  get 'home/index' #devise tutorial default "landing page"
  root to: "pages#index"
  #devise_for :users
  devise_for :users, :controllers => { :registrations => 'signups' }
  #resources :users
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#  root 'pages#index'
  get 'commercial' => 'pages#commercial'
  get 'residential' => 'pages#residential'
  get 'quote' => 'pages#quote'
  get 'index' => 'pages#index'
  get 'signups-auth' => 'pages#signups-auth'
  post 'signups-auth', action: :create, controller: "passwords"

#  get 'users/:id' => 'users#show', as: :user
#  post 'sign_up' => 'users#show'

  authenticate :user do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    get 'welcome' => redirect('/admin')

    resources :interventions
    get 'get_form_customer_selector', action: :get_form_customer_selector, controller: 'interventions'
    get 'get_form_building_selector', action: :get_form_building_selector, controller: 'interventions'
    get 'get_form_battery_selector',  action: :get_form_battery_selector,  controller: 'interventions'
    get 'get_form_column_selector',   action: :get_form_column_selector,   controller: 'interventions'
    get 'get_form_elevator_selector', action: :get_form_elevator_selector, controller: 'interventions'
    
  end


end

app/models/address.rb
class Address < ApplicationRecord
    has_one :customer
    has_one :building
end

app/models/battery.rb
class Battery < ApplicationRecord
    belongs_to :building
    belongs_to :employee
    has_many :column
end

app/models/building.rb
class Building < ApplicationRecord
    belongs_to :customer
    belongs_to :address
    has_one :buildingdetail
    has_one :battery
    has_one :employee
end

app/models/buildingdetail.rb
class Buildingdetail < ApplicationRecord
    belongs_to :building
end

app/models/column.rb
class Column < ApplicationRecord
    #self.inheritance_column = :_type_disabled
    has_many :elevator
    belongs_to :battery
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :address
    belongs_to :user
    has_many :building
end

app/models/dim_customer.rb
class DimCustomer < PostgresRecord
end

app/models/elevator.rb
class Elevator < ApplicationRecord
  #self.inheritance_column = :_type_disabled
  belongs_to :column
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
end

app/models/fact_contact.rb
class FactContact < PostgresRecord
end

app/models/fact_elevator.rb
class FactElevator < PostgresRecord
end

app/models/fact_quote.rb
class FactQuote < PostgresRecord
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :attachment
    def attachment_blob_id
#        self.attachment.blob_id
        self.attachment.blob_id
    end
end

#    if self.attachment.blob_id
#        def attachment_blob_id
#            self.attachment.blob_id
#        end
#    else
#        def attachment_blob_id
#            return "-"
#        end
#    end

#    scope :attachment_blob_id, -> { where(self.attachment.blob_id) }
#
#    def attachment_blob_id?
#        self.attachment.blob_id
#    end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
#  belongs_to :employees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :employee
  has_one :customer
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/buildingdetails_controller.rb
class BuildingdetailsController < ApplicationController
  before_action :set_buildingdetail, only: %i[ show edit update destroy ]

  # GET /buildingdetails or /buildingdetails.json
  def index
    @buildingdetails = Buildingdetail.all
  end

  # GET /buildingdetails/1 or /buildingdetails/1.json
  def show
  end

  # GET /buildingdetails/new
  def new
    @buildingdetail = Buildingdetail.new
  end

  # GET /buildingdetails/1/edit
  def edit
  end

  # POST /buildingdetails or /buildingdetails.json
  def create
    @buildingdetail = Buildingdetail.new(buildingdetail_params)

    respond_to do |format|
      if @buildingdetail.save
        format.html { redirect_to @buildingdetail, notice: "Buildingdetail was successfully created." }
        format.json { render :show, status: :created, location: @buildingdetail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buildingdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildingdetails/1 or /buildingdetails/1.json
  def update
    respond_to do |format|
      if @buildingdetail.update(buildingdetail_params)
        format.html { redirect_to @buildingdetail, notice: "Buildingdetail was successfully updated." }
        format.json { render :show, status: :ok, location: @buildingdetail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buildingdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildingdetails/1 or /buildingdetails/1.json
  def destroy
    @buildingdetail.destroy
    respond_to do |format|
      format.html { redirect_to buildingdetails_url, notice: "Buildingdetail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buildingdetail
      @buildingdetail = Buildingdetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buildingdetail_params
      params.require(:buildingdetail).permit(:building_id, :information, :information_value)
    end
end

app/helpers/buildingdetails_helper.rb
module BuildingdetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildingdetails/_form.html.erb
<%= form_with(model: buildingdetail, local: true) do |form| %>
  <% if buildingdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buildingdetail.errors.count, "error") %> prohibited this buildingdetail from being saved:</h2>

      <ul>
      <% buildingdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :building_id %>
    <%= form.number_field :building_id %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information %>
  </div>

  <div class="field">
    <%= form.label :information_value %>
    <%= form.text_field :information_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildingdetails/edit.html.erb
<h1>Editing Buildingdetail</h1>

<%= render 'form', buildingdetail: @buildingdetail %>

<%= link_to 'Show', @buildingdetail %> |
<%= link_to 'Back', buildingdetails_path %>

app/views/buildingdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildingdetails</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Information</th>
      <th>Information value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildingdetails.each do |buildingdetail| %>
      <tr>
        <td><%= buildingdetail.building_id %></td>
        <td><%= buildingdetail.information %></td>
        <td><%= buildingdetail.information_value %></td>
        <td><%= link_to 'Show', buildingdetail %></td>
        <td><%= link_to 'Edit', edit_buildingdetail_path(buildingdetail) %></td>
        <td><%= link_to 'Destroy', buildingdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buildingdetail', new_buildingdetail_path %>

app/views/buildingdetails/new.html.erb
<h1>New Buildingdetail</h1>

<%= render 'form', buildingdetail: @buildingdetail %>

<%= link_to 'Back', buildingdetails_path %>

app/views/buildingdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Building:</strong>
  <%= @buildingdetail.building_id %>
</p>

<p>
  <strong>Information:</strong>
  <%= @buildingdetail.information %>
</p>

<p>
  <strong>Information value:</strong>
  <%= @buildingdetail.information_value %>
</p>

<%= link_to 'Edit', edit_buildingdetail_path(@buildingdetail) %> |
<%= link_to 'Back', buildingdetails_path %>